### ISSUE TITLE
Allow notification categories and dbus configuration files to be installed

### ISSUE THREAD

**Issue by kimmoli** [sailfishos/sdk-harbour-rpmvalidator#76]
As the notifications are now allowed, the notification categories should also be allowed to be written in the assumed location:

```
/usr/share/lipstick/notificationcategories/
```

Also the dbus is allowed, and notifications have remoteActions over dbus, the .service and .xml should also be allowed to be written in their assumed locations:

```
/usr/share/dbus-1/services/
/usr/share/dbus-1/interfaces/
```

...feel free to speculate.

**Comment by kimmoli** [comment]
Related TJC https://together.jolla.com/question/126847

**Comment by pvuorela** [comment]
Old one here, but I'd be tempted to close this and the TJC question for the notification categories part. Categories are more of grouping things and a group with a single entry is not too much of a group. Earlier the notification system didn't allow all the properties without a separate file, but that has gotten better and if there are any more shortcomings, we should add support on the notification api rather than making categories.

**Comment by Thaodan** [comment]
What do you advice apps that use notification categories to do, drop the file and let the notification system group them on its own?
